### ISSUE TITLE
any reason to use openssl crate instead of rust-native rustls crate?

### ISSUE THREAD

**Issue by ghost** [Florob/rust-xmpp#13]
question

**Comment by Florob** [comment]
Apart from some dependency updates prompted by security reports this crate is not really under active development. Also be aware it isn't very usable in its current state.
As I recall it the code predates rustls (or at least rustls was still very unfinished) so initial development couldn't use it. SCRAM authentication also uses various other cryptographic primitives exposed by openssl. I doubt rustls provides/exposes these, which is not to say they couldn't be replaced by other Rust crates.
